import {
  readPreferredAppLanguage,
  resolveAppLanguageDirection,
  useOptionalAppLanguage,
} from './appLanguage.tsx';

const TEACHER_LANGUAGE_COPY = {
  en: {
    nav: {
      createQuiz: 'Create Quiz',
      myQuizzes: 'My Quizzes',
      discover: 'Discover',
      reports: 'Reports',
      classes: 'Classes',
      settings: 'Settings',
      helpCenter: 'Help Center',
      logOut: 'Log out',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Profile, notification and classroom preferences for your teacher workspace.',
      saveChanges: 'Save Changes',
      tabs: {
        profile: 'Profile',
        notifications: 'Notifications',
        security: 'Security',
        appearance: 'Language',
      },
      feedback: {
        profileIncomplete: 'Profile details are incomplete.',
        fillSecurity: 'Fill all password fields before saving.',
        passwordsMismatch: 'New password and confirmation do not match.',
        saved: 'Settings saved.',
        passwordUpdated: 'Settings saved and password updated.',
        saveFailed: 'We could not save your changes right now.',
      },
      profile: {
        title: 'Profile Information',
        changeAvatar: 'Change Avatar',
        firstName: 'First Name',
        lastName: 'Last Name',
        email: 'Email Address',
        school: 'School / Organization',
      },
      notifications: {
        title: 'Notification Preferences',
        featureUpdates: 'Email updates on new features',
        weeklyReports: 'Weekly class performance reports',
        studentJoinAlerts: 'Student join alerts',
        marketingEmails: 'Marketing and promotional emails',
      },
      security: {
        title: 'Security Settings',
        description: 'Update the password used for email and password sign-in.',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
        providerManaged: 'This account signs in with Google, so password changes are managed by your identity provider.',
      },
      appearance: {
        title: 'Interface Language',
        description: 'Choose the language used in the teacher workspace.',
        themeTitle: 'Theme',
        themeDescription: '',
        light: 'Light',
        dark: 'Dark',
        languageTitle: 'Interface Language',
        languageDescription: 'Choose whether this teacher settings interface is shown in English, Hebrew, or Arabic.',
        english: 'English',
        hebrew: 'Hebrew',
        arabic: 'Arabic',
      },
    },
  },
  he: {
    nav: {
      createQuiz: 'יצירת חידון',
      myQuizzes: 'החידונים שלי',
      discover: 'גילוי',
      reports: 'דוחות',
      classes: 'כיתות',
      settings: 'הגדרות',
      helpCenter: 'מרכז עזרה',
      logOut: 'התנתקות',
    },
    settings: {
      title: 'הגדרות',
      subtitle: 'העדפות פרופיל, התראות וכיתה עבור סביבת המורה שלך.',
      saveChanges: 'שמור שינויים',
      tabs: {
        profile: 'פרופיל',
        notifications: 'התראות',
        security: 'אבטחה',
        appearance: 'שפה',
      },
      feedback: {
        profileIncomplete: 'פרטי הפרופיל אינם מלאים.',
        fillSecurity: 'יש למלא את כל שדות הסיסמה לפני השמירה.',
        passwordsMismatch: 'הסיסמה החדשה ושדה האימות אינם תואמים.',
        saved: 'ההגדרות נשמרו.',
        passwordUpdated: 'ההגדרות נשמרו והסיסמה עודכנה.',
        saveFailed: 'לא הצלחנו לשמור את השינויים כרגע.',
      },
      profile: {
        title: 'פרטי פרופיל',
        changeAvatar: 'החלפת אווטאר',
        firstName: 'שם פרטי',
        lastName: 'שם משפחה',
        email: 'כתובת דוא"ל',
        school: 'בית ספר / ארגון',
      },
      notifications: {
        title: 'העדפות התראות',
        featureUpdates: 'עדכוני מייל על פיצרים חדשים',
        weeklyReports: 'דוחות שבועיים על ביצועי הכיתה',
        studentJoinAlerts: 'התראות על הצטרפות תלמידים',
        marketingEmails: 'מיילים שיווקיים וקידומיים',
      },
      security: {
        title: 'הגדרות אבטחה',
        description: 'עדכן את הסיסמה שמשמשת להזדהות עם אימייל וסיסמה.',
        currentPassword: 'סיסמה נוכחית',
        newPassword: 'סיסמה חדשה',
        confirmPassword: 'אימות סיסמה חדשה',
        providerManaged: 'החשבון הזה נכנס עם Google, לכן שינוי הסיסמה מתבצע אצל ספק ההזדהות שלך.',
      },
      appearance: {
        title: 'שפת ממשק',
        description: 'בחר את שפת הממשק של סביבת המורה.',
        themeTitle: 'ערכת עיצוב',
        themeDescription: '',
        light: 'בהיר',
        dark: 'כהה',
        languageTitle: 'שפת ממשק',
        languageDescription: 'בחר אם מסך ההגדרות של המורה יוצג באנגלית, בעברית או בערבית.',
        english: 'אנגלית',
        hebrew: 'עברית',
        arabic: 'ערבית',
      },
    },
  },
  ar: {
    nav: {
      createQuiz: 'إنشاء اختبار',
      myQuizzes: 'اختباراتي',
      discover: 'استكشاف',
      reports: 'التقارير',
      classes: 'الصفوف',
      settings: 'الإعدادات',
      helpCenter: 'مركز المساعدة',
      logOut: 'تسجيل الخروج',
    },
    settings: {
      title: 'الإعدادات',
      subtitle: 'إعدادات الملف الشخصي والإشعارات والصف لواجهة المعلّم.',
      saveChanges: 'حفظ التغييرات',
      tabs: {
        profile: 'الملف الشخصي',
        notifications: 'الإشعارات',
        security: 'الأمان',
        appearance: 'اللغة',
      },
      feedback: {
        profileIncomplete: 'بيانات الملف الشخصي غير مكتملة.',
        fillSecurity: 'املأ جميع حقول كلمة المرور قبل الحفظ.',
        passwordsMismatch: 'كلمة المرور الجديدة وتأكيدها غير متطابقين.',
        saved: 'تم حفظ الإعدادات.',
        passwordUpdated: 'تم حفظ الإعدادات وتحديث كلمة المرور.',
        saveFailed: 'تعذر حفظ التغييرات الآن.',
      },
      profile: {
        title: 'معلومات الملف الشخصي',
        changeAvatar: 'تغيير الصورة الرمزية',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        email: 'عنوان البريد الإلكتروني',
        school: 'المدرسة / المؤسسة',
      },
      notifications: {
        title: 'تفضيلات الإشعارات',
        featureUpdates: 'رسائل بريدية عن الميزات الجديدة',
        weeklyReports: 'تقارير أسبوعية عن أداء الصف',
        studentJoinAlerts: 'تنبيهات انضمام الطلاب',
        marketingEmails: 'رسائل تسويقية وترويجية',
      },
      security: {
        title: 'إعدادات الأمان',
        description: 'حدّث كلمة المرور المستخدمة لتسجيل الدخول بالبريد الإلكتروني وكلمة المرور.',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور الجديدة',
        providerManaged: 'هذا الحساب يستخدم Google لتسجيل الدخول، لذلك تتم إدارة كلمة المرور لدى موفر الهوية.',
      },
      appearance: {
        title: 'لغة الواجهة',
        description: 'اختر اللغة المستخدمة في مساحة عمل المعلّم.',
        themeTitle: 'النسق',
        themeDescription: '',
        light: 'فاتح',
        dark: 'داكن',
        languageTitle: 'لغة الواجهة',
        languageDescription: 'اختر ما إذا كانت واجهة المعلّم ستظهر بالإنجليزية أو العبرية أو العربية.',
        english: 'الإنجليزية',
        hebrew: 'العبرية',
        arabic: 'العربية',
      },
    },
  },
} as const;

export function useTeacherLanguage() {
  const context = useOptionalAppLanguage();
  const language = context?.language || readPreferredAppLanguage();
  const direction = context?.direction || resolveAppLanguageDirection(language);
  return {
    language,
    direction,
    copy: TEACHER_LANGUAGE_COPY[language as keyof typeof TEACHER_LANGUAGE_COPY] || TEACHER_LANGUAGE_COPY.en,
  };
}
