import { useAppLanguage } from './appLanguage.tsx';

const TEACHER_LANGUAGE_COPY = {
  en: {
    nav: {
      createQuiz: 'Create Quiz',
      myQuizzes: 'My Quizzes',
      discover: 'Discover',
      reports: 'Reports',
      classes: 'Classes',
      settings: 'Settings',
      helpCenter: 'Help Center',
      logOut: 'Log out',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Profile, notification and classroom preferences for your teacher workspace.',
      saveChanges: 'Save Changes',
      tabs: {
        profile: 'Profile',
        notifications: 'Notifications',
        security: 'Security',
        appearance: 'Appearance',
      },
      feedback: {
        profileIncomplete: 'Profile details are incomplete.',
        fillSecurity: 'Fill all security fields to update the password preference.',
        passwordsMismatch: 'New password and confirmation do not match.',
        saved: 'Settings saved locally.',
      },
      profile: {
        title: 'Profile Information',
        changeAvatar: 'Change Avatar',
        firstName: 'First Name',
        lastName: 'Last Name',
        email: 'Email Address',
        school: 'School / Organization',
      },
      notifications: {
        title: 'Notification Preferences',
        featureUpdates: 'Email updates on new features',
        weeklyReports: 'Weekly class performance reports',
        studentJoinAlerts: 'Student join alerts',
        marketingEmails: 'Marketing and promotional emails',
      },
      security: {
        title: 'Security Settings',
        description: 'This demo saves the preference locally. Connect a real auth backend to enforce password changes.',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
      },
      appearance: {
        title: 'Appearance',
        description: 'Theme and interface language are stored locally for your teacher workspace.',
        themeTitle: 'Theme',
        themeDescription: 'Theme preference is stored and can be wired into a global theme switch later.',
        light: 'Light',
        dark: 'Dark',
        languageTitle: 'Interface Language',
        languageDescription: 'Choose whether this teacher settings interface is shown in English, Hebrew, or Arabic.',
        english: 'English',
        hebrew: 'Hebrew',
        arabic: 'Arabic',
      },
    },
  },
  he: {
    nav: {
      createQuiz: 'יצירת חידון',
      myQuizzes: 'החידונים שלי',
      discover: 'גילוי',
      reports: 'דוחות',
      classes: 'כיתות',
      settings: 'הגדרות',
      helpCenter: 'מרכז עזרה',
      logOut: 'התנתקות',
    },
    settings: {
      title: 'הגדרות',
      subtitle: 'העדפות פרופיל, התראות וכיתה עבור סביבת המורה שלך.',
      saveChanges: 'שמור שינויים',
      tabs: {
        profile: 'פרופיל',
        notifications: 'התראות',
        security: 'אבטחה',
        appearance: 'מראה',
      },
      feedback: {
        profileIncomplete: 'פרטי הפרופיל אינם מלאים.',
        fillSecurity: 'יש למלא את כל שדות האבטחה כדי לעדכן את העדפת הסיסמה.',
        passwordsMismatch: 'הסיסמה החדשה ושדה האימות אינם תואמים.',
        saved: 'ההגדרות נשמרו מקומית.',
      },
      profile: {
        title: 'פרטי פרופיל',
        changeAvatar: 'החלפת אווטאר',
        firstName: 'שם פרטי',
        lastName: 'שם משפחה',
        email: 'כתובת דוא"ל',
        school: 'בית ספר / ארגון',
      },
      notifications: {
        title: 'העדפות התראות',
        featureUpdates: 'עדכוני מייל על פיצרים חדשים',
        weeklyReports: 'דוחות שבועיים על ביצועי הכיתה',
        studentJoinAlerts: 'התראות על הצטרפות תלמידים',
        marketingEmails: 'מיילים שיווקיים וקידומיים',
      },
      security: {
        title: 'הגדרות אבטחה',
        description: 'בגרסת הדמו הזו ההעדפה נשמרת מקומית. כדי לאכוף שינויי סיסמה צריך לחבר מנגנון הזדהות אמיתי.',
        currentPassword: 'סיסמה נוכחית',
        newPassword: 'סיסמה חדשה',
        confirmPassword: 'אימות סיסמה חדשה',
      },
      appearance: {
        title: 'מראה ושפה',
        description: 'ערכת העיצוב ושפת הממשק נשמרות מקומית עבור סביבת המורה שלך.',
        themeTitle: 'ערכת עיצוב',
        themeDescription: 'העדפת ערכת העיצוב נשמרת, וניתן לחבר אותה בהמשך למתג גלובלי.',
        light: 'בהיר',
        dark: 'כהה',
        languageTitle: 'שפת ממשק',
        languageDescription: 'בחר אם מסך ההגדרות של המורה יוצג באנגלית, בעברית או בערבית.',
        english: 'אנגלית',
        hebrew: 'עברית',
        arabic: 'ערבית',
      },
    },
  },
  ar: {
    nav: {
      createQuiz: 'إنشاء اختبار',
      myQuizzes: 'اختباراتي',
      discover: 'استكشاف',
      reports: 'التقارير',
      classes: 'الصفوف',
      settings: 'الإعدادات',
      helpCenter: 'مركز المساعدة',
      logOut: 'تسجيل الخروج',
    },
    settings: {
      title: 'الإعدادات',
      subtitle: 'إعدادات الملف الشخصي والإشعارات والصف لواجهة المعلّم.',
      saveChanges: 'حفظ التغييرات',
      tabs: {
        profile: 'الملف الشخصي',
        notifications: 'الإشعارات',
        security: 'الأمان',
        appearance: 'المظهر',
      },
      feedback: {
        profileIncomplete: 'بيانات الملف الشخصي غير مكتملة.',
        fillSecurity: 'املأ جميع حقول الأمان لتحديث تفضيل كلمة المرور.',
        passwordsMismatch: 'كلمة المرور الجديدة وتأكيدها غير متطابقين.',
        saved: 'تم حفظ الإعدادات محليًا.',
      },
      profile: {
        title: 'معلومات الملف الشخصي',
        changeAvatar: 'تغيير الصورة الرمزية',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        email: 'عنوان البريد الإلكتروني',
        school: 'المدرسة / المؤسسة',
      },
      notifications: {
        title: 'تفضيلات الإشعارات',
        featureUpdates: 'رسائل بريدية عن الميزات الجديدة',
        weeklyReports: 'تقارير أسبوعية عن أداء الصف',
        studentJoinAlerts: 'تنبيهات انضمام الطلاب',
        marketingEmails: 'رسائل تسويقية وترويجية',
      },
      security: {
        title: 'إعدادات الأمان',
        description: 'في هذه النسخة التجريبية يتم حفظ التفضيل محليًا. لفرض تغيير كلمات المرور يجب ربط نظام مصادقة حقيقي.',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور الجديدة',
      },
      appearance: {
        title: 'المظهر واللغة',
        description: 'يتم حفظ نسق الواجهة ولغتها محليًا في مساحة عمل المعلّم.',
        themeTitle: 'النسق',
        themeDescription: 'يتم حفظ تفضيل النسق ويمكن ربطه لاحقًا بمفتاح عام.',
        light: 'فاتح',
        dark: 'داكن',
        languageTitle: 'لغة الواجهة',
        languageDescription: 'اختر ما إذا كانت واجهة المعلّم ستظهر بالإنجليزية أو العبرية أو العربية.',
        english: 'الإنجليزية',
        hebrew: 'العبرية',
        arabic: 'العربية',
      },
    },
  },
} as const;

export function useTeacherLanguage() {
  const { language, direction } = useAppLanguage();
  return {
    language,
    direction,
    copy: TEACHER_LANGUAGE_COPY[language as keyof typeof TEACHER_LANGUAGE_COPY] || TEACHER_LANGUAGE_COPY.en,
  };
}
